### ISSUE TITLE
Is there any way to create custom syntax

### ISSUE THREAD

**Issue by Bricktheworld** [tomyeh/markd#12]
I would like to support a bunch of reddit's markdown syntax but I am unsure of how to go about doing this. Would it be possible for me to support the spoiler syntax of: ">!some text here<!" in the library? Also another one is "^some super script". Sorry I am so vague about what I have tried, it's just that I do not know how this library works and am completely lost haha

Thank you guys! Stay safe :)

**Comment by tomyeh** [comment]
It can be done by implementing your own `InlineSyntax`. Then, you can include them when instantiating `InlineParser` in your app. That said, they all can be done in your app, without putting them in this library.

You can refer to `ExtensionSet` for how it is done.

**Comment by Bricktheworld** [comment]
@tomyeh 

Thank you for your reply! So now I have some more questions, where exactly do I use the InlineParser?  Because in the `markdownToHtml` function, I see the `extensionSet` prop, but then in the `ExtensionSet` constructor, how do I use the `InlineParser` / `InlineSyntax`? Because as far as I can tell, the `ExtensionSet` only takes a list of block and inline syntaxes as props. Would it be possible to provide an example of how this is properly done? 

Thank you so much :)

**Comment by tomyeh** [comment]
Please take a look at `test/markdown_test.dart`. There are a lot of examples there.
